1 - Import Libraries

In [2]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import tensorflow as tf

2 - Load Model

In [4]:
model = tf.keras.models.load_model('audiobooks_model.h5')

2 - Load Dataset

In [5]:
raw_data = np.genfromtxt('audiobooks_data_new.csv', delimiter=',')
raw_data_inputs = raw_data[:,1:]
raw_data_inputs

array([[1.1880e+03, 1.1880e+03, 5.3300e+00, 5.3300e+00, 0.0000e+00,
        8.9100e+00, 1.2000e-01, 0.0000e+00, 0.0000e+00, 3.9000e+01],
       [6.4800e+02, 6.4800e+02, 5.3300e+00, 5.3300e+00, 0.0000e+00,
        8.9100e+00, 4.8000e-01, 0.0000e+00, 0.0000e+00, 9.1000e+01],
       [2.1600e+03, 2.1600e+03, 7.6900e+00, 7.6900e+00, 0.0000e+00,
        8.9100e+00, 0.0000e+00, 6.8040e+02, 0.0000e+00, 0.0000e+00],
       [1.6740e+03, 3.3480e+03, 8.0000e+00, 1.6000e+01, 1.0000e+00,
        1.0000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.7000e+01],
       [2.1600e+03, 2.1600e+03, 5.6600e+00, 5.6600e+00, 0.0000e+00,
        8.9100e+00, 1.2000e-01, 7.3440e+02, 0.0000e+00, 1.9800e+02],
       [2.1600e+03, 2.1600e+03, 6.5800e+00, 6.5800e+00, 0.0000e+00,
        8.9100e+00, 0.0000e+00, 7.3440e+02, 0.0000e+00, 0.0000e+00],
       [2.1600e+03, 2.1600e+03, 5.3300e+00, 5.3300e+00, 0.0000e+00,
        8.9100e+00, 0.0000e+00, 6.8040e+02, 0.0000e+00, 0.0000e+00],
       [2.1600e+03, 2.1600e+03, 7.9300e+0

3 - Scale Data

In [6]:
scaled_raw_data_inputs = preprocessing.scale(raw_data_inputs)
scaled_raw_data_inputs

array([[-0.78766791, -0.86092523, -0.29464249, -0.38463886, -0.5       ,
         0.15572737,  0.3008153 , -0.77524925,  0.        , -0.07945635],
       [-1.89015799, -1.58237096, -0.29464249, -0.38463886, -0.5       ,
         0.15572737,  2.85892963, -0.77524925,  0.        ,  0.54656339],
       [ 1.19681423,  0.43767707, -0.16196623, -0.25580113, -0.5       ,
         0.15572737, -0.55188948,  0.98329742,  0.        , -0.54897116],
       [ 0.20457316,  2.02485767, -0.14453842,  0.19786055,  2.        ,
         0.72090885, -0.55188948, -0.77524925,  0.        , -0.22392245],
       [ 1.19681423,  0.43767707, -0.2760903 , -0.36662342, -0.5       ,
         0.15572737,  0.3008153 ,  1.12286462,  0.        ,  1.8347194 ],
       [ 1.19681423,  0.43767707, -0.22436905, -0.31639854, -0.5       ,
         0.15572737, -0.55188948,  1.12286462,  0.        , -0.54897116],
       [ 1.19681423,  0.43767707, -0.29464249, -0.38463886, -0.5       ,
         0.15572737, -0.55188948,  0.98329742

4 - Prediction

In [10]:
scaled_raw_data_outputs = np.argmax(model.predict(scaled_raw_data_inputs),1)
scaled_raw_data_outputs

1/1 [==============================] - 0s 81ms/step


array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1], dtype=int64)

5 - Export Result

In [36]:
data = raw_data.copy()
data = pd.DataFrame(data)
data

0       1       2       3       4    5      6     7        8    9   \
0    1.0  1188.0  1188.0    5.33    5.33  0.0   8.91  0.12     0.00  0.0   
1    2.0   648.0   648.0    5.33    5.33  0.0   8.91  0.48     0.00  0.0   
2    3.0  2160.0  2160.0    7.69    7.69  0.0   8.91  0.00   680.40  0.0   
3    4.0  1674.0  3348.0    8.00   16.00  1.0  10.00  0.00     0.00  0.0   
4    5.0  2160.0  2160.0    5.66    5.66  0.0   8.91  0.12   734.40  0.0   
5    6.0  2160.0  2160.0    6.58    6.58  0.0   8.91  0.00   734.40  0.0   
6    7.0  2160.0  2160.0    5.33    5.33  0.0   8.91  0.00   680.40  0.0   
7    8.0  2160.0  2160.0    7.93    7.93  0.0   8.91  0.03   680.40  0.0   
8    9.0  2160.0  2160.0    4.09    4.09  0.0   8.91  0.00   680.40  0.0   
9   10.0  2160.0  2160.0    5.61    5.61  0.0   8.91  0.00     0.00  0.0   
10  11.0  2160.0  2160.0   10.13   10.13  1.0  10.00  0.34  1166.40  0.0   
11  12.0  1620.0  1620.0    5.33    5.33  0.0   8.91  0.00     0.00  0.0   
12  13.0  1620.0  1620.0    5.33    5.33  1.0   6.00  0.00     0.00  0.0   
13  14.0  1620.0  1620.0    5.33    5.33  0.0   8.91  0.29  1188.00  0.0   
14  15.0   648.0   648.0    5.33    5.33  0.0   8.91  0.00   696.60  0.0   
15  16.0  1188.0  1188.0    7.68    7.68  0.0   8.91  0.00   696.60  0.0   
16  17.0  1188.0  1188.0    8.48    8.48  0.0   8.91  0.00     0.00  0.0   
17  18.0  2160.0  2160.0    5.33    5.33  0.0   8.91  0.00     0.00  0.0   
18  19.0  1188.0  1188.0    5.69    5.69  0.0   8.91  0.00     0.00  0.0   
19  20.0  1620.0  1620.0    5.61    5.61  0.0  10.00  0.00     0.00  0.0   
20  21.0  1242.0  2484.0   16.80   33.59  1.0  10.00  0.00   680.40  0.0   
21  22.0   756.0  1512.0    5.33   10.67  0.0   8.91  0.00     0.00  0.0   
22  23.0  1188.0  1188.0  104.00  104.00  0.0  10.00  0.00     0.00  0.0   
23  24.0  1620.0  1620.0    8.00    8.00  0.0   1.00  0.35     0.00  0.0   
24  25.0  1188.0  1188.0    5.33    5.33  0.0   8.91  0.18   142.56  0.0   
25  26.0  1188.0  1188.0    5.33    5.33  0.0   3.00  0.00    64.80  0.0   
26  27.0  2160.0  2160.0    5.33    5.33  0.0   8.91  0.02     0.00  0.0   
27  28.0  1620.0  1620.0   24.16   24.16  1.0  10.00  0.40     0.00  0.0   
28  29.0  1134.0  2268.0   10.13   20.27  1.0  10.00  0.00     0.00  0.0   
29  30.0  1476.0  4428.0    6.93   20.80  0.0   9.00  0.00   172.80  0.0   

       10  
0    39.0  
1    91.0  
2     0.0  
3    27.0  
4   198.0  
5     0.0  
6     0.0  
7   152.0  
8     0.0  
9    21.0  
10   15.0  
11    1.0  
12    8.0  
13   27.0  
14    0.0  
15    0.0  
16   32.0  
17    4.0  
18   30.0  
19    2.0  
20    0.0  
21    0.0  
22    0.0  
23   12.0  
24    4.0  
25  321.0  
26    0.0  
27    0.0  
28  102.0  
29  282.0

In [37]:
data.shape

(30, 11)

In [41]:
scaled_raw_data_outputs = pd.DataFrame(scaled_raw_data_outputs)
scaled_raw_data_outputs

0
0   0
1   0
2   0
3   1
4   0
5   0
6   0
7   0
8   0
9   1
10  0
11  1
12  1
13  0
14  0
15  0
16  1
17  1
18  1
19  1
20  0
21  1
22  1
23  0
24  0
25  1
26  1
27  0
28  1
29  1

In [44]:
data = pd.concat([data, scaled_raw_data_outputs], axis=1)
data

0       1       2       3       4    5      6     7        8    9   \
0    1.0  1188.0  1188.0    5.33    5.33  0.0   8.91  0.12     0.00  0.0   
1    2.0   648.0   648.0    5.33    5.33  0.0   8.91  0.48     0.00  0.0   
2    3.0  2160.0  2160.0    7.69    7.69  0.0   8.91  0.00   680.40  0.0   
3    4.0  1674.0  3348.0    8.00   16.00  1.0  10.00  0.00     0.00  0.0   
4    5.0  2160.0  2160.0    5.66    5.66  0.0   8.91  0.12   734.40  0.0   
5    6.0  2160.0  2160.0    6.58    6.58  0.0   8.91  0.00   734.40  0.0   
6    7.0  2160.0  2160.0    5.33    5.33  0.0   8.91  0.00   680.40  0.0   
7    8.0  2160.0  2160.0    7.93    7.93  0.0   8.91  0.03   680.40  0.0   
8    9.0  2160.0  2160.0    4.09    4.09  0.0   8.91  0.00   680.40  0.0   
9   10.0  2160.0  2160.0    5.61    5.61  0.0   8.91  0.00     0.00  0.0   
10  11.0  2160.0  2160.0   10.13   10.13  1.0  10.00  0.34  1166.40  0.0   
11  12.0  1620.0  1620.0    5.33    5.33  0.0   8.91  0.00     0.00  0.0   
12  13.0  1620.0  1620.0    5.33    5.33  1.0   6.00  0.00     0.00  0.0   
13  14.0  1620.0  1620.0    5.33    5.33  0.0   8.91  0.29  1188.00  0.0   
14  15.0   648.0   648.0    5.33    5.33  0.0   8.91  0.00   696.60  0.0   
15  16.0  1188.0  1188.0    7.68    7.68  0.0   8.91  0.00   696.60  0.0   
16  17.0  1188.0  1188.0    8.48    8.48  0.0   8.91  0.00     0.00  0.0   
17  18.0  2160.0  2160.0    5.33    5.33  0.0   8.91  0.00     0.00  0.0   
18  19.0  1188.0  1188.0    5.69    5.69  0.0   8.91  0.00     0.00  0.0   
19  20.0  1620.0  1620.0    5.61    5.61  0.0  10.00  0.00     0.00  0.0   
20  21.0  1242.0  2484.0   16.80   33.59  1.0  10.00  0.00   680.40  0.0   
21  22.0   756.0  1512.0    5.33   10.67  0.0   8.91  0.00     0.00  0.0   
22  23.0  1188.0  1188.0  104.00  104.00  0.0  10.00  0.00     0.00  0.0   
23  24.0  1620.0  1620.0    8.00    8.00  0.0   1.00  0.35     0.00  0.0   
24  25.0  1188.0  1188.0    5.33    5.33  0.0   8.91  0.18   142.56  0.0   
25  26.0  1188.0  1188.0    5.33    5.33  0.0   3.00  0.00    64.80  0.0   
26  27.0  2160.0  2160.0    5.33    5.33  0.0   8.91  0.02     0.00  0.0   
27  28.0  1620.0  1620.0   24.16   24.16  1.0  10.00  0.40     0.00  0.0   
28  29.0  1134.0  2268.0   10.13   20.27  1.0  10.00  0.00     0.00  0.0   
29  30.0  1476.0  4428.0    6.93   20.80  0.0   9.00  0.00   172.80  0.0   

       10  0   
0    39.0   0  
1    91.0   0  
2     0.0   0  
3    27.0   1  
4   198.0   0  
5     0.0   0  
6     0.0   0  
7   152.0   0  
8     0.0   0  
9    21.0   1  
10   15.0   0  
11    1.0   1  
12    8.0   1  
13   27.0   0  
14    0.0   0  
15    0.0   0  
16   32.0   1  
17    4.0   1  
18   30.0   1  
19    2.0   1  
20    0.0   0  
21    0.0   1  
22    0.0   1  
23   12.0   0  
24    4.0   0  
25  321.0   1  
26    0.0   1  
27    0.0   0  
28  102.0   1  
29  282.0   1

In [45]:
data.to_csv('audiobooks_data_new_result.csv', index=False)